import test from 'node:test';
import assert from 'node:assert/strict';
import { stages } from '../src/data/stages.js';
import { getInitialParty } from '../src/engine/partyEngine.js';
import { trainParty } from '../src/engine/growthEngine.js';
import { normalizeSaveData } from '../src/engine/saveEngine.js';
import {
  createDefeatCheckpoint, createVictoryCheckpoint, getCampBattleStageId,
  getCampTrainingAvailability, getUnlockedStageIds, normalizeLastBattleResult,
} from '../src/engine/campaignProgress.js';

const copy = value => JSON.parse(JSON.stringify(value));
const freeze = value => {
  if (value && typeof value === 'object' && !Object.isFrozen(value)) {
    Object.values(value).forEach(freeze);
    Object.freeze(value);
  }
  return value;
};
const battleData = () => {
  const party = getInitialParty();
  return {
    screen: 'battle', selectedStage: stages[1], party,
    units: party.slice(1).map(unit => ({ ...unit, hp: 2, level: 3, exp: 77, baseAtk: unit.baseAtk + 2,
      baseDef: unit.baseDef + 2, maxHp: unit.maxHp + 4, status: [{ type: 'burn', turns: 2 }],
      moved: true, acted: true, guard: true, skillCooldowns: { test: 3 } })),
    gold: 987, inventory: { potion: 1, remedy: 2 }, gearInventory: ['ironSword', 'mageRobe'],
    gearEnhance: { ironSword: 3 }, supportPoints: { hero_lina: 45 }, exploration: { claimed: ['kept'] },
    clearedStages: [1], unlockedStages: [1, 2], stageRewardClaimed: false,
    trainingUsed: false, dispatchUsed: true, selectedUnit: 'bram', turn: 'enemy', mode: 'attack',
    battleLoot: { gold: 120, items: { potion: 4 }, gear: ['chainArmor'] },
    stageMastery: { 1: { stars: 4 } }, careerStats: { defeats: 2 }, hazards: [{ x: 2, y: 2 }],
  };
};

test('retreat preserves earned growth and all prior rewards while healing the roster and locking training', () => {
  const data = freeze(battleData()), before = copy(data);
  const receipt = createDefeatCheckpoint(data);
  assert.deepEqual(receipt.reward, { gold: 0, potion: 0 });
  assert.equal(receipt.checkpoint.screen, 'camp');
  assert.deepEqual(receipt.checkpoint.lastBattleResult, { stageId: 2, outcome: 'defeat' });
  assert.equal(receipt.checkpoint.trainingUsed, true);
  assert.equal(receipt.checkpoint.dispatchUsed, true);
  assert.equal(receipt.checkpoint.stageRewardClaimed, false);
  for (const field of ['gold', 'inventory', 'gearInventory', 'gearEnhance', 'supportPoints', 'exploration', 'clearedStages', 'unlockedStages', 'stageMastery', 'careerStats']) {
    assert.deepEqual(receipt.checkpoint[field], data[field]);
  }
  assert.deepEqual(receipt.checkpoint.battleLoot, { gold: 0, items: {}, gear: [] });
  assert.deepEqual(receipt.checkpoint.hazards, []);
  for (const unit of receipt.checkpoint.party) {
    const live = data.units.find(member => member.id === unit.id) || data.party.find(member => member.id === unit.id);
    for (const field of ['level', 'exp', 'maxHp', 'baseAtk', 'baseDef', 'equipment']) assert.deepEqual(unit[field], live[field]);
    assert.equal(unit.hp, unit.maxHp);
    assert.equal(unit.acted, false);
    assert.equal(unit.moved, false);
    assert.equal(unit.guard, false);
    assert.deepEqual(unit.status, []);
    assert.deepEqual(unit.skillCooldowns, {});
  }
  assert.deepEqual(data, before);
});

test('unused training is locked after defeat and cannot be regenerated by repeated retreat or save reload', () => {
  let data = battleData();
  const initialStats = data.party.map(unit => [unit.id, unit.baseAtk, unit.baseDef]);
  for (let attempt = 0; attempt < 5; attempt++) {
    const checkpoint = createDefeatCheckpoint({ ...data, units: data.party }).checkpoint;
    data = normalizeSaveData(copy(checkpoint), '1.99.161');
    assert.equal(getCampTrainingAvailability(data).allowed, false);
    assert.match(getCampTrainingAvailability(data).reason, /전투에서 승리한 뒤/);
    assert.equal(trainParty(data.party, 'attack', data.trainingUsed).count, 0);
    assert.deepEqual(data.party.map(unit => [unit.id, unit.baseAtk, unit.baseDef]), initialStats);
    assert.deepEqual(data.clearedStages, [1]);
    assert.deepEqual(data.unlockedStages, [1, 2]);
  }
});

test('training done before battle stays consumed after defeat, including bench members', () => {
  const data = battleData();
  const trained = trainParty(data.party, 'attack');
  const checkpoint = createDefeatCheckpoint({ ...data, party: trained.units, units: [], trainingUsed: true, dispatchUsed: false }).checkpoint;
  assert.equal(checkpoint.dispatchUsed, false);
  assert.equal(checkpoint.trainingUsed, true);
  assert.deepEqual(checkpoint.party.map(unit => [unit.baseAtk, unit.exp]), trained.units.map(unit => [unit.baseAtk, unit.exp]));
  assert.equal(trainParty(checkpoint.party, 'focus', checkpoint.trainingUsed).count, 0);
});

test('successful settlement preserves the existing one-training allowance for first clears and winning replays', () => {
  const data = battleData();
  const defeated = createDefeatCheckpoint(data).checkpoint;
  const settlement = { party: defeated.party, reward: { gold: 700, potion: 1 }, careerStats: { victories: 2 }, stageMastery: {}, message: '승리' };
  const victory = createVictoryCheckpoint(defeated, settlement);
  assert.deepEqual(victory.checkpoint.lastBattleResult, { stageId: 2, outcome: 'victory' });
  assert.equal(victory.checkpoint.trainingUsed, false);
  assert.equal(getCampTrainingAvailability(victory.checkpoint).allowed, true);
  assert.deepEqual(victory.checkpoint.unlockedStages, [1, 2, 3]);
  const replay = createVictoryCheckpoint(victory.checkpoint, settlement);
  assert.deepEqual(replay.reward, { gold: 0, potion: 0 });
  assert.equal(replay.checkpoint.trainingUsed, false);
  assert.equal(getCampTrainingAvailability(replay.checkpoint).allowed, true);
  assert.equal(replay.checkpoint.gold, victory.checkpoint.gold);
});

test('all thirty failed current chapters recommend retry without unlocking their successor', () => {
  for (const { id } of stages) {
    const clearedStages = Array.from({ length: id - 1 }, (_, index) => index + 1);
    const context = { selectedStageId: id, clearedStages, lastBattleResult: { stageId: id, outcome: 'defeat' } };
    assert.equal(getCampBattleStageId(context), id);
    assert.equal(getUnlockedStageIds(clearedStages).includes(id + 1), false);
  }
});

test('failed replay remains the preferred retry while other legitimate unlocks and old late clears survive', () => {
  const clearedStages = [1, 2, 8, 30];
  assert.equal(getCampBattleStageId({ selectedStageId: 2, clearedStages, lastBattleResult: { stageId: 2, outcome: 'defeat' } }), 2);
  assert.deepEqual(getUnlockedStageIds(clearedStages), [1, 2, 3, 8, 30]);
  assert.equal(getCampBattleStageId({ selectedStageId: 30, clearedStages, lastBattleResult: { stageId: 30, outcome: 'defeat' } }), 30);
  assert.equal(getCampBattleStageId({ selectedStageId: 8, clearedStages, lastBattleResult: { stageId: 8, outcome: 'victory' } }), 3);
  assert.equal(getCampBattleStageId({ selectedStageId: 9, clearedStages, lastBattleResult: { stageId: 9, outcome: 'defeat' } }), 3, 'Locked legacy failure cannot bypass the first unplayed chapter');
  assert.equal(getCampBattleStageId({ selectedStageId: 999, clearedStages: [] }), 1);
  assert.equal(getCampBattleStageId({ clearedStages: stages.map(stage => stage.id) }), null);
});

test('only exact legacy camp retreat evidence migrates to defeat without rewriting saves or progress', () => {
  const data = battleData();
  const raw = { ...data, screen: 'camp', campMessage: `${stages[1].title}에서 철수했습니다. 부대를 재정비합니다.` };
  freeze(raw);
  const migrated = normalizeSaveData(raw, '1.99.161');
  assert.deepEqual(migrated.lastBattleResult, { stageId: 2, outcome: 'defeat' });
  assert.equal(migrated.trainingUsed, true);
  assert.deepEqual(migrated.clearedStages, raw.clearedStages);
  assert.deepEqual(migrated.unlockedStages, [1, 2]);
  for (const unrelated of [
    { ...raw, campMessage: '부대를 재정비합니다.' },
    { ...raw, campMessage: `${stages[2].title}에서 철수했습니다. 부대를 재정비합니다.` },
    { ...raw, stageRewardClaimed: true },
    { ...raw, stageRewardClaimed: undefined },
    { ...raw, screen: 'battle' },
    { ...raw, lastBattleResult: null },
  ]) {
    const restored = normalizeSaveData(unrelated, '1.99.161');
    assert.equal(restored.lastBattleResult, null);
    assert.equal(restored.trainingUsed, false);
  }
  const explicit = normalizeSaveData({ ...raw, lastBattleResult: { stageId: 1, outcome: 'victory' } }, '1.99.161');
  assert.deepEqual(explicit.lastBattleResult, { stageId: 1, outcome: 'victory' });
  assert.equal(explicit.trainingUsed, false);
  assert.equal(Object.hasOwn(raw, 'lastBattleResult'), false);
  assert.equal(raw.trainingUsed, false);
});

test('new result sanitation rejects malformed and inherited records while old normal training saves remain compatible', () => {
  for (const raw of [null, [], {}, { stageId: 0, outcome: 'defeat' }, { stageId: stages.length + 1, outcome: 'defeat' },
    { stageId: '1', outcome: 'defeat' }, { stageId: 1, outcome: 'won' }, Object.create({ stageId: 1, outcome: 'defeat' })]) {
    assert.equal(normalizeLastBattleResult(raw), null);
  }
  const defaultSave = normalizeSaveData({ party: getInitialParty(), trainingUsed: false }, '1.99.161');
  assert.equal(defaultSave.lastBattleResult, null);
  assert.equal(getCampTrainingAvailability(defaultSave).allowed, true);
  assert.equal(getCampTrainingAvailability({ ...defaultSave, trainingUsed: true }).allowed, false);
  const saved = normalizeSaveData({ ...defaultSave, lastBattleResult: { stageId: 1, outcome: 'defeat' }, trainingUsed: false }, '1.99.161');
  assert.equal(saved.trainingUsed, true);
  assert.deepEqual(normalizeSaveData(copy(saved), '1.99.161').lastBattleResult, saved.lastBattleResult);
  assert.throws(() => createDefeatCheckpoint({ selectedStage: { id: stages.length + 1 } }), /전장을 확인/);
});

test('old defeat-to-campaign saves remain training locked when continuing into town', () => {
  const raw = freeze({ ...battleData(), version: '1.99.160', screen: 'campaign',
    campMessage: `${stages[1].title}에서 철수했습니다. 부대를 재정비합니다.` });
  const before = copy(raw);
  const continued = normalizeSaveData(raw, '1.99.161');
  assert.equal(continued.screen, 'campaign');
  assert.deepEqual(continued.lastBattleResult, { stageId: 2, outcome: 'defeat' });
  assert.equal(continued.trainingUsed, true);
  assert.equal(getCampTrainingAvailability(continued).allowed, false);
  const town = normalizeSaveData({ ...continued, screen: 'camp' }, '1.99.161');
  assert.equal(town.screen, 'camp');
  assert.equal(getCampTrainingAvailability(town).allowed, false);
  assert.equal(trainParty(town.party, 'attack', town.trainingUsed).count, 0);
  assert.equal(getCampBattleStageId(town), 2);
  for (const field of ['party', 'units', 'clearedStages', 'gold', 'inventory', 'gearInventory', 'gearEnhance']) {
    assert.deepEqual(town[field], continued[field]);
  }
  assert.deepEqual(raw, before);
  for (const context of [{ ...raw, stageRewardClaimed: true }, { ...raw, lastBattleResult: null },
    { ...raw, campMessage: '전투 준비를 마쳤습니다.' }]) {
    const normal = normalizeSaveData(context, '1.99.161');
    assert.equal(normal.lastBattleResult, null);
    assert.equal(normal.trainingUsed, false);
  }
});
